@startuml

skin rose

entity product {
*id: int <<PK>>
--
*name: varchar
*price: float
image_path: varchar
}

entity product_detail {
*id: int <<PK>>
--
*product_id: int <<FK>>
*name: varchar
*value: varchar
}

entity customer {
*id: int <<PK>>
--
*billing_address_id: int <<FK>>
*email_address: varchar
tel_number: varchar
}

entity address {
*id: int <<PK>>
--
*first_name
*last_name
*street: varchar
*house_number: varchar
*zip_code: varchar
*city: varchar
*country: varchar
}

entity order {
*id: int <<PK>>
--
*customer_id: int <<FK>>
*delivery_address_id: int <<FK>>
*payment_method: varchar
date_ordered: timestamp

}

entity order_product {
*id: int <<PK>>
--
*order_id: int <<FK>>
*product_id: int <<FK>>
}

entity user {
*id: int <<PK>>
--
*customer_id: int <<FK>>
*username: varchar
*password: varchar
}

customer "1".."n" order
order "1".."n" order_product
product "1".."n" order_product
address "1".."n" customer
address "1".."n" order
product "1".."n" product_detail
user "1".."n" customer





@enduml